### ISSUE TITLE
kernel 4.1 check is incorrect, breaks config-pin

### ISSUE THREAD

**Issue by plauria** [cdsteinkuehler/beaglebone-universal-io#33]
Hi guys, 2 days ago there was a commit that checked for kernel 4.1; the commit is " adapt to kernel (4.1.x) changes..." which simply checks for the existance of  /sys/devices/platform/. This is not correct, because this directory exists on 3.8.13-bone47. Thus config-pin is currently broken on non-4.1 kernels, giving a spurious "pinmux file not found" error when you try to change a pin's function. Commenting out the changed lines fixes the issue. I suggest a simple 'uname -r' replacement but that is up to you.

**Comment by cdsteinkuehler** [comment]
Fixed by #34
