### ISSUE TITLE
pinmux file not found on Linux arm 3.14.41-ti-r63 

### ISSUE THREAD

**Issue by AdamSLevy** [cdsteinkuehler/beaglebone-universal-io#35]
Trying to set up a serial connection for a GPS.

I have also tried RCN's Really Simple Cape Manager. No success on setting up pins.

$ sudo setserial -g /dev/ttyO*
/dev/ttyO0, UART: 8250, Port: 0x0000, IRQ: 88
/dev/ttyO1, UART: 8250, Port: 0x0000, IRQ: 89
/dev/ttyO2, UART: 8250, Port: 0x0000, IRQ: 90
/dev/ttyO4, UART: 8250, Port: 0x0000, IRQ: 61
/dev/ttyO5, UART: 8250, Port: 0x0000, IRQ: 62

**Comment by larivierec** [comment]
this is likely because it looks for /sys/devices/ocp/ does not follow the same layout then it did it previous kernels.
