### ISSUE TITLE
make install not working

### ISSUE THREAD

**Issue by Nafina** [cdsteinkuehler/beaglebone-universal-io#38]
Hello,
when i do 
#make install 
I get the following error:
compiling file cape-universal-00A0.dts
dtc: invalid option -- @

**Comment by cdsteinkuehler** [comment]
You need to use a newer version of dtc that supports overlays (the -@ flag).  The easiest way to do this is on the BeagleBone itself.  If you're on the 'Bone and getting this error, update the device-tree-compiler package (making sure you've got RCN's repos.rcn-ee.net repository enabled).

**Comment by Nafina** [comment]
Thank you!
